language: go
install: go get -v github.com/spf13/hugo
script:
- hugo -v --ignoreCache
before_deploy: pip install --user awscli
deploy:
  provider: script
  access_key_id: AKIAJNGBFCZ4H7YV5KUA
  secret_access_key:
    secure: pLl2a9B2CxzjXje5YuF5LAXk6mhdshe68smZm2q9sXKZugNKEScK0+xZYT6zCudEwzuqE+QTKusK50S6mv6KUI7UUO1j1dU8Xh76kwrucIK7v0rWDGerfJxBPyLQj6nYZ8s68M8MH+6Lh/1M8b/xhIlu8mErOm+Ft3mgrUx7C4bj4dWicz8+aZaozpLn0rnSlloqIdzYJ5YAwo2hKrwEWi3S597Pw0W7ZJrIbDweyT1E+SLWaAqYjTb8gOcZngtcnJNTosdQM2ZDBIVMw3eZBuMncnWo/Z7gTete8DccwWjIGvOENl9RQAcCdtLplBrI7c9oRYYCVxqYOYBNkxxKJ19P8gf2Q6yzxkLtQtfbh6PdEaKwXBa/M8dtqOds3A4e3503S/ObAoIj0ihD+uBMwHNYPkXetkU4v2XNkJQDSuvdaNkOFf1M+n3R9c9vBHXL9mUHJYU0vtthjTHIBwObDRbg8+dM27/tgyQsq19tIsVgDNbEOQfRnexCkKz43GEX+HnoE20P1f3VzGnwIpt8UM8KswcG49uVg9/zsHoNiQB12pXDWt3e2UTd1ry4FmVKwH3d4pq1NBrTlw0vHxniyW0VjjOZRQJOZZs5yuRNI3K1jb3Tw6ehGPFCc8Sj/iFLrbGjpeRRoDYb45vYO6hqHEBSzkrYPoG8bDFasqY8b1A=
  script: ~/.local/bin/aws s3 sync public s3://somrc-website --region=us-east-1 --delete
  skip_cleanup: true
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nem2p@virginia.edu
  slack:
    secure: S27Eetiy8VLj6jBz37wMX+9wl40PgdrHm347oIGFikJ+ci2XCkJCXyq+nDkt9YfYw83RA/sTezy6GbASxnYry5BItsUD1gJCcQ7YvUtAu7mjLcZZxd3mCJeydnPZOHFAPEPPwgH8EvD5sVwtPE/dluouG8aQdYSqji1ZiVAsLBr+PYIOrDeVDEYRE2hO0SUKfnxuVUnKwNVccahTeIcELXm8JGIhtf3/o+RkUT4YsjNQ2XH3RugGArcWvZex6WwZgeML83uPA0fuEb1nnBDkuRGsvJlgO6XNcaiDLyqQoj+LUNCzEjKcNWUrloFIR+I9nZBcqsWjmKtj3GA0Uzl678OJ5/CZvjmwjjrnbV7ENdde/MZXJr/MNq5mI6UZCayZJXrXNS4cVKI9ITWA09omEOhS3Z/FUiSR0MzldCnL9X5AP2MkxBUfW6c6vgb5Xkt8hB4BLHFNjvDew9oxWeHnPF5q+KsUEMJNk0cXPxNilgRfDd6YzCMQUzwi/e1eSX2QCK86ZDla+21QJQEgS+0ZnJQaxWFCg1swRoBw40828Mcz1N1BPV8X5n4QcKAgUyl2BfxVylWnEdua68YpCsU2U7T7bKUo2JxAbgpnG3P3g15o4R4EVK/r8Ztwnkqib9nVyMLTyC7QGLjGLQ/F2Hjvp+QfNZ6DnXITP4CHfkLE+3Q=
    on_success: change
    on_failure: always
