language: go

install:
  - go get -v github.com/spf13/hugo
  - sudo pip install --upgrade pip
  - pip install --user awscli
  #- pip install --user -r requirements.txt

script:
  - hugo -v --ignoreCache

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - nmagee@virginia.edu

before_deploy: 
  # - sudo pip install --upgrade pip
  # - pip install --user awscli

deploy:
  # sync all files to s3
  - provider: script
    script: ~/.local/bin/aws s3 sync public s3://$BUCKET_NAME --region=us-east-1 --delete
    skip_cleanup: true
    on:
      branch: master
  # clear the cloudfront cache so changes are seen
  - provider: script
    script: ~/.local/bin/aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
    on:
      branch: master
  # sync all files to staging s3 bucket
  - provider: script
    script: ~/.local/bin/aws s3 sync public s3://$BUCKET_NAME_STAGING --region=us-east-1 --delete
    skip_cleanup: true
    on:
      branch: staging
  # invalidate staging cache
  - provider: script
    script: ~/.local/bin/aws cloudfront create-invalidation --distribution-id $STAGING_DISTRIBUTION_ID --paths "/*"
    on:
      branch: staging
