baseurl = "http://somrc-website.s3-website-us-east-1.amazonaws.com/"
title = "Research Computing"
publishdir = "public"
languageCode = "en-us"
theme = "hugo-theme-bootstrap4-somrc"
# theme = "sp-minimal"
copyright = "&copy;2017 UVA School of Medicine"
paginate        = 5
disableRSS = true
disableSitemap = true
disable404 = true
[permalinks]
  post = "/:year/:month/:title/"
[params]
  subtitle    = "Research Computing"
  authorImage = "ec2-icon.png"
  #"single" or "multi"
  renderType = "multi"
  #"simple" or "original"
  themeStyle = "simple"
  googleAnalytics = ""
  name = "UVA School of Medicine"
  description = "HPC / Cloud Computing for Researchers"
  pageNotFoundTitle = "404 - Page not found"
