baseurl = "/"
title = "Research Computing"
publishdir = "public"
languageCode = "en-us"
theme = "somrc-bootstrap-v4"
copyright = " {year} By the Rector and Visitors of the University of Virginia "
paginate = 20
disableKinds= ["RSS","404"]
ignoreCache = true
# date_format = "January 2, 2006"

[permalinks]
  post = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  featured = "featured"

[params]
  subtitle = "Research Computing"
  authorImage = "ec2-icon.png"
  #"single" or "multi"
  renderType = "multi"
  # "simple" or "original"
  themeStyle = "simple"
  # googleAnalytics = "UA-90358528-1"
  name = "UVA School of Medicine"
  description = "Enabling scientific breakthroughs at scale with advanced computing"
  pageNotFoundTitle = "404 - Page not found"

[params.sidebar]
  # Optional about block for sidebar (can be Markdown)
  about = "Enabling scientific breakthroughs at scale via advanced computing."
  # How many posts to show on the sidebar (Default: 5)
  num_recent_posts = 5

[params.sharingicons]
  # Hide the sharing icons on posts? (Default: false)
  hide = true

[outputs]
    home = [ "HTML", "JSON"]
    page = [ "HTML"]
