baseurl = "/"
title = "Research Computing"
publishdir = "public"
languageCode = "en-us"
theme = "rc-bootstrap-v4"
copyright = " {year} "
paginate = 20
disableKinds= ["RSS","404"]
ignoreCache = true
# date_format = "January 2, 2006"
summaryLength = 100
timeout = "60000"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  featured = "featured"

[params]
  subtitle = "UVA Research Computing"
  authorImage = "ec2-icon.png"
  #"single" or "multi"
  renderType = "multi"
  # "simple" or "original"
  themeStyle = "simple"
  # googleAnalytics = "UA-90358528-1"
  name = "UVA Research Computing"
  description = "Creating innovative solutions for researchers"
  pageNotFoundTitle = "404 - Page not found"
  rivannaJsonUrl = "http://apidata.uvarc.io/rivanna-software.json"

[params.pricing]
  # Set STORAGE / VM PRICES globally below:
  storageProject = 60
  storageValue = 45
  storageZfs = 30
  storageIvy = 45
  ivyVmSmall = 999
  ivyVmMedium = 1499
  ivyVmLarge = 1999
  omero = 60

[params.sidebar]
  # Optional about block for sidebar (can be Markdown)
  about = "Enabling scientific breakthroughs at scale via advanced computing."
  # How many posts to show on the sidebar (Default: 5)
  num_recent_posts = 5

[params.sharingicons]
  # Hide the sharing icons on posts? (Default: false)
  hide = true

[outputs]
  home = [ "HTML", "JSON"]
  page = [ "HTML"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
