name: Hugo Build CI

on:
  push:
    branches:
    - master
    - staging
  pull_request:
    branches:
    - master
    - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site using a custom hugo container
      env:  
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        BUCKET_NAME_STAGING: ${{ secrets.BUCKET_NAME_STAGING }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        STAGING_DISTRIBUTION_ID: ${{ secrets.STAGING_DISTRIBUTION_ID }}
        MAX_AGE: ${{ secrets.MAX_AGE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        docker run -it -e TRAVIS_BRANCH=${GITHUB_REF##*/} -e BUCKET_NAME=$BUCKET_NAME -e DISTRIBUTION_ID=$DISTRIBUTION_ID \
          -e BUCKET_NAME_STAGING=$BUCKET_NAME_STAGING -e STAGING_DISTRIBUTION_ID=$STAGING_DISTRIBUTION_ID \
          -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          -e MAX_AGE=$MAX_AGE uvarc/hugo-build:v2 /root/build-site.sh
